# Generated by Django 3.2.9 on 2021-11-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
